# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize:
    person.mushroom:
      entity_picture: "/local/mushrooms.jpeg"

# Text to speech
tts:
  - platform: google_translate

climate:
  - platform: demo

light:
  - platform: demo

switch:
  - platform: demo

cover:
  - platform: demo

media_player:
  - platform: demo

person:
  - name: Mushroom
    id: mush1234

lovelace: !include ui-lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes
#   development_repo: /workspaces/home-assistant-frontend