# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize:
    person.anne_therese:
      entity_picture: "/local/mushrooms.jpeg"

# Text to speech
tts:
  - platform: google_translate

climate:
  - platform: demo

light:
  - platform: demo

switch:
  - platform: demo

cover:
  - platform: demo

media_player:
  - platform: demo

device_tracker:
  - platform: demo

person:
  - name: Anne Therese
    id: anne_therese
    device_trackers:
      - device_tracker.demo_anne_therese

alarm_control_panel:
  - platform: manual
    name: Alarm panel 1
  - platform: manual
    name: Alarm panel 2

group:
  alarm_group:
    name: Alarm control panel group
    entities:
      - alarm_control_panel.alarm_panel_1
      - alarm_control_panel.alarm_panel_2

lovelace: !include ui-lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes
#   development_repo: /workspaces/home-assistant-frontend