title: Mushroom
views:
  - title: Showcase
    cards:
      - type: grid
        title: Lights
        cards:
          - type: custom:mushroom-light-card
            entity: light.bed_light
          - type: custom:mushroom-light-card
            entity: light.bed_light
            show_brightness_control: true
          - type: custom:mushroom-light-card
            entity: light.bed_light
            name: Custom name and icon
            icon: mdi:robot-outline
            show_brightness_control: true
        columns: 1
        square: false
      - type: grid
        title: Switchs
        cards:
          - type: custom:mushroom-switch-card
            entity: switch.decorative_lights
          - type: custom:mushroom-switch-card
            entity: switch.decorative_lights
            name: Custom name and icon
            icon: mdi:chef-hat
        columns: 1
        square: false
      - type: grid
        title: Person
        cards:
          - type: custom:mushroom-person-card
            entity: person.anne_therese
          - type: custom:mushroom-person-card
            entity: person.anne_therese
            name: Custom name and icon
            icon: mdi:face-woman
          - type: custom:mushroom-person-card
            entity: person.anne_therese
            name: Use entity picture
            use_entity_picture: true
          - type: custom:mushroom-person-card
            entity: person.anne_therese
            name: No tap action
            tap_action:
              action: none
          - type: custom:mushroom-person-card
            entity: person.anne_therese
            name: No tap action
            tap_action:
              action: none
          - type: grid
            cards:
              - type: button
                name: Home
                icon: mdi:home
                tap_action:
                  action: call-service
                  service: device_tracker.see
                  service_data:
                    dev_id: demo_anne_therese
                    location_name: home
              - type: button
                name: Not Home
                icon: mdi:home-export-outline
                tap_action:
                  action: call-service
                  service: device_tracker.see
                  service_data:
                    dev_id: demo_anne_therese
                    location_name: not_home
              - type: button
                name: Unknown
                icon: mdi:help
                tap_action:
                  action: call-service
                  service: device_tracker.see
                  service_data:
                    dev_id: demo_anne_therese
                    location_name: unknown
            columns: 3
            square: false
        columns: 1
        square: false